# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170727_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 11, 22, 33, 998558), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 28, 11, 22, 33, 998583), verbose_name='修改时间'),
        ),
    ]
